"""
SK Framework — Core Engine
Main orchestration engine and BaseModule abstract class.
All attack modules extend BaseModule.
"""

import abc
import asyncio
import json
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from pathlib import Path

from pydantic import BaseModel, Field

from src.core.config import config
from src.utils.llm_client import LLMClient, LLMRequest, LLMResponse
from src.utils.scoring import ScoringEngine, ScoreResult
from src.utils.logger import get_logger

log = get_logger("engine")


# ─── Enums ───

class ModuleCategory(Enum):
    PROMPT_INJECTION = "prompt_injection"
    JAILBREAK = "jailbreak"
    DATA_EXFILTRATION = "data_exfil"
    ADVERSARIAL = "adversarial"
    MODEL_EXTRACTION = "model_extraction"
    DATA_POISONING = "data_poisoning"
    DOS = "dos_attack"


class Difficulty(Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


# ─── Models ───

class ModuleMetadata(BaseModel):
    """Metadata every module must provide."""
    name: str                          # e.g. "basic_prompt_injection"
    display_name: str                  # e.g. "Basic Prompt Injection"
    version: str                       # e.g. "1.0.0"
    category: ModuleCategory
    difficulty: Difficulty
    owasp_mapping: str | None = None   # e.g. "ML01" — maps to OWASP ML Top 10
    description: str = ""
    author: str = "SK Community"
    tags: list[str] = Field(default_factory=list)


class ModuleOption(BaseModel):
    """A configurable parameter for a module."""
    name: str
    default: Any = None
    description: str = ""
    required: bool = False


class AttackResult(BaseModel):
    """Full result of running an attack module."""
    module: str
    provider: str
    model: str
    payload: str
    response: str
    score: ScoreResult
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict[str, Any] = Field(default_factory=dict)

    def export_json(self, export_dir: str = "exports") -> Path:
        """Export result to a JSON file."""
        path = Path(export_dir)
        path.mkdir(parents=True, exist_ok=True)
        
        file_path = path / f"attack_{self.module}_{self.timestamp.strftime('%Y%m%d_%H%M%S')}.json"
        with open(file_path, "w") as f:
            f.write(self.model_dump_json(indent=2))
        return file_path

    def export_markdown(self, export_dir: str = "exports") -> Path:
        """Export result to a human-readable Markdown file."""
        path = Path(export_dir)
        path.mkdir(parents=True, exist_ok=True)
        
        file_path = path / f"attack_{self.module}_{self.timestamp.strftime('%Y%m%d_%H%M%S')}.md"
        
        md_content = f"""# Attack Report: {self.module}
- **Date:** {self.timestamp.isoformat()}
- **Target:** {self.provider} ({self.model})
- **Result:** {self.score.result.value.upper()}
- **Score:** {self.score.score:.2f} (Confidence: {self.score.confidence:.0%})

## Summary
{self.score.details}

## Payload
```text
{self.payload}
```

## Response
```text
{self.response}
```

## Signals Detected
{chr(10).join([f'- {s}' for s in self.score.signals])}

---
*Generated by SK Framework*
"""
        with open(file_path, "w") as f:
            f.write(md_content)
        return file_path


# ─── Base Module ───

class BaseModule(abc.ABC):
    """
    Abstract base class for all SK attack modules.
    """

    def __init__(self):
        self.llm = LLMClient()
        self.scorer = ScoringEngine()

    @property
    @abc.abstractmethod
    def metadata(self) -> ModuleMetadata:
        """Return module metadata."""
        ...

    def get_options(self) -> list[ModuleOption]:
        """
        Return list of configurable options for this module.
        """
        return []

    @abc.abstractmethod
    def get_payloads(self) -> list[str]:
        """Return list of attack payloads this module can use."""
        ...

    @abc.abstractmethod
    async def run(
        self,
        target_provider: str,
        target_model: str,
        payload: str | None = None,
        system_prompt: str | None = None,
        on_event: Any | None = None,
        **kwargs
    ) -> AttackResult:
        """Execute the attack."""
        ...

    async def _send_and_score(
        self,
        prompt: str,
        target_provider: str,
        target_model: str,
        system_prompt: str | None = None,
        payload: str | None = None,
        expected_flag: str | None = None,
        base_url: str | None = None,
        api_key: str | None = None,
    ) -> tuple[LLMResponse, ScoreResult]:
        """
        Convenience method: sends a prompt to the target LLM and scores the result.
        """
        request = LLMRequest(
            prompt=prompt,
            system_prompt=system_prompt,
            provider=target_provider,
            model=target_model,
            base_url=base_url,
            api_key=api_key,
        )

        response = await self.llm.send(request)

        score = self.scorer.score(
            response_text=response.content,
            attack_payload=payload or prompt,
            expected_flag=expected_flag,
        )

        return response, score


# ─── Engine ───

class SKEngine:
    """
    Main engine. Discovers, loads, and runs attack modules.
    """

    def __init__(self):
        self._modules: dict[str, type[BaseModule]] = {}
        self._discover_modules()

    def _discover_modules(self):
        """Auto-discover all modules in src/modules/."""
        from src.core.plugin_loader import discover_modules
        self._modules = discover_modules()
        log.info("modules_loaded", count=len(self._modules), names=list(self._modules.keys()))

    def list_modules(self) -> list[ModuleMetadata]:
        """Return metadata for all loaded modules."""
        return [mod().metadata for mod in self._modules.values()]

    def get_module(self, name: str) -> BaseModule:
        """Get a module instance by name."""
        if name not in self._modules:
            raise ValueError(f"Module '{name}' not found. Available: {list(self._modules.keys())}")
        return self._modules[name]()

    async def run_module(
        self,
        module_name: str,
        target_provider: str | None = None,
        target_model: str | None = None,
        payload: str | None = None,
        system_prompt: str | None = None,
        on_event: Any | None = None,
        **kwargs
    ) -> AttackResult:
        """
        Run an attack module end-to-end.
        """
        provider = target_provider or config.default_provider
        model = target_model or config.default_model

        log.info("running_module", module=module_name, provider=provider, model=model)

        module = self.get_module(module_name)
        result = await module.run(
            target_provider=provider,
            target_model=model,
            payload=payload,
            system_prompt=system_prompt,
            on_event=on_event,
            **kwargs
        )

        log.info(
            "module_complete",
            module=module_name,
            result=result.score.result.value,
            confidence=result.score.confidence,
        )
        return result
